# This script creates a function to programattically create a code book using
# the column names of a data frame

# I decided to only include the variables that actually appear in my tidy data.

createCodeBook <- function(input){
        # Get the names of all the columns in the input data set
        names <- colnames(input)
        
        explanation <- names
        
        # I'm going to define standard_deviation and mean globally in the .md, so I want
        # want to remove those.
        explanation <- gsub(pattern = "standard_deviation",
                            replacement = "",
                            explanation)
        
        explanation <- gsub(pattern = "mean",
                            replacement = "",
                            explanation)
        
        # Likewise with x, y, and z
        explanation <- gsub(pattern = "[x-z]",
                            replacement = "",
                            explanation)
        
        # Start programatically writing explanations for the data.
      
        explanation[1] <- "A number identifying test subjects. Ranges from 1 to 30. "
        
        explanation[2] <- "The position the test subject was in for a given run. "
          
        # All of the vars containing the word "time" were measured in the time domain.
        explanation <- gsub(pattern = "time",
                            replacement = "This variable was originally derived from the raw time domain data ",
                            explanation)
        
        # All vars containing the word "frequency" underwent Fourier transforms.
        explanation <- gsub(pattern = "frequenc",
                            replacement = "This variable was derived from frequency domain data generated by applying Fast Fourier Transforms to the time domain data ",
                            explanation)
        
        explanation <- gsub(pattern = "accelerometer",
                            replacement = "Accelerometers were the source of this data. ",
                            explanation)
        
        explanation <- gsub(pattern = "groscope",
                            replacement = "Gyroscopes were the source of this data. ",
                            explanation)
        
        explanation <- gsub(pattern = "magnitude",
                            replacement = "This is the three dimensional magnitude of the associated variable. ",
                            explanation)
        
        explanation <- gsub(pattern = "weighted",
                            replacement = "Mean frequency determined by taking the weighted average of the frequency components. ",
                            explanation)
        
        explanation <- gsub(pattern = "bod",
                            replacement = "on the component of acceleration resulting from the motion of the subject's body. ",
                            explanation)
        
        explanation <- gsub(pattern = "gravit",
                            replacement = "on the component of acceleration resulting from gravity. ",
                            explanation)
        
        explanation <- gsub(pattern = "jerk",
                            replacement = "Jerk was determined by taking the time derivative of acceleration for the associated variable. ",
                            explanation)
        
        # Remove the underscores, as they will clutter up my codebook.
        explanation <- gsub(pattern = "_",
                            replacement = "",
                            explanation)
        
        # Create a text string out of the explanations
        codebook <- paste("* ", names, " <br> ", explanation, "\n")
        
        # Save the resulting data to a md file.
        write.table(codebook, "codebook_basis.md", quote = FALSE,
                                row.names = FALSE, col.names = FALSE)
}
